#ifndef ITEM_H
#define ITEM_H

#include "global.h"


//// 全局变量

// 声明位图句柄
HBITMAP m_hBackgroundBmp;
HBITMAP m_hBackground01Bmp;
HBITMAP m_hBackground02Bmp;
HBITMAP m_hBackground03Bmp;
HBITMAP m_hBackground04Bmp;
HBITMAP m_hHeroBmp;
HBITMAP m_hGameStartButtonBmp;
HBITMAP m_hBangreplaceBmp;
HBITMAP m_hGunsightBmp;
HBITMAP m_hRestartButtonBmp;
HBITMAP m_hHeroBmpRe;
HBITMAP m_hBangGif;
HBITMAP m_hHero01Bmp;
HBITMAP m_hHero01BmpRe;
HBITMAP m_hHero02Bmp;
HBITMAP m_hHero02BmpRe;
HBITMAP m_hHero03Bmp;
HBITMAP m_hHero03BmpRe;
HBITMAP m_hHero03replaceBmpRe;
HBITMAP m_hHero04Bmp;
HBITMAP m_hHero04BmpRe;
HBITMAP m_hWizard01Bmp;
HBITMAP m_hWizard01BmpRe;
HBITMAP m_hWizard02Bmp;
HBITMAP m_hWizard02BmpRe;
HBITMAP m_hWizard03Bmp;
HBITMAP m_pointerBmp;
HBITMAP m_seaBmp;
HBITMAP m_cloudBmp;
HBITMAP m_hWizard01replaceBmpRe;
HBITMAP m_ball;
HBITMAP m_hWizard02replaceBmpRe;
HBITMAP m_balleffect;
HBITMAP m_text01;
HBITMAP m_text02;
HBITMAP m_text03;
HBITMAP m_text04;
HBITMAP m_text05;
HBITMAP m_tomb;
HBITMAP m_help;
HBITMAP m_helppage;
HBITMAP m_menu;
HBITMAP m_reload;
HBITMAP m_pause;
HBITMAP m_pause_page;
HBITMAP m_result[7];
HBITMAP m_overbackground;
HBITMAP m_rocket;
HBITMAP m_heroicon[3];
HBITMAP m_wizardicon[3];
HBITMAP m_pick_background;
HBITMAP m_aidBmp;
// 声明英雄、建筑、地形、按钮
Hero          m_hero[MAX_HERO_NUM];
Terrian       m_terrian[MAX_TERRIAN_NUM];
GameButton    m_gameStartButton;
GameButton	  m_helpButton;
GameButton	  m_help_startButton;
GameButton    m_gamgRestartButton;
GameButton    m_gamgRestartButton2;
GameButton    m_menuButton;
GameButton    m_pauseButton;
Bang          m_bang[MAX_BANG_NUM];
Gunsight      m_gunsight;
Herolife	  m_herolife[MAX_HERO_NUM];
Force         m_force;
Weapon        m_weapon[MAX_BANG_NUM];
VirtialButton m_VB01;
VirtialButton m_VB02;
VirtialButton m_background01;
VirtialButton m_background02;
VirtialButton m_background03;
VirtialButton m_background04;
Aid           m_aid;
// 声明游戏状态
GameStatus gameStatus;

#endif